[package]
name = "sbtc-core"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
once_cell.workspace = true
regex.workspace = true
stacks-core.workspace = true
stacks-rs.workspace = true
thiserror.workspace = true
