[package]
name = "sbtc-core"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Package that exposes primitives for working with the Stacks sBTC token"
homepage = "https://github.com/stacks-network/sbtc"
readme = "README.md"

[dependencies]
bdk.workspace = true
bitcoin.workspace = true
log.workspace = true
once_cell.workspace = true
regex.workspace = true
stacks-core.path = "../stacks-core"
thiserror.workspace = true
