[package]
name = "stacks-core"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Package that exposes primitives for working with the Stacks blockchain"
homepage = "https://github.com/stacks-network/sbt"
readme = "README.md"

[dependencies]
bitcoin.workspace = true
hex.workspace = true
once_cell.workspace = true
regex.workspace = true
ripemd.workspace = true
secp256k1.workspace = true
serde = { workspace = true, features = ["derive"] }
sha2.workspace = true
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true
rand.workspace = true
